name: pretty_playground
description: Playground for pretty todo app.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.22.0 <1.23.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flare_flutter:
  spritewidget:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/flares/
